export const salesData = [
  {
    id: 1,
    region: "North",
    category: "Electronics",
    quarter: "Q1",
    year: 2023,
    sales: 12400,
  },
  {
    id: 2,
    region: "North",
    category: "Electronics",
    quarter: "Q2",
    year: 2023,
    sales: 14300,
  },
  {
    id: 3,
    region: "North",
    category: "Electronics",
    quarter: "Q1",
    year: 2024,
    sales: 15200,
  },
  {
    id: 4,
    region: "North",
    category: "Electronics",
    quarter: "Q2",
    year: 2024,
    sales: 16800,
  },
  {
    id: 5,
    region: "North",
    category: "Furniture",
    quarter: "Q1",
    year: 2023,
    sales: 9100,
  },
  {
    id: 6,
    region: "North",
    category: "Furniture",
    quarter: "Q2",
    year: 2023,
    sales: 8700,
  },
  {
    id: 7,
    region: "North",
    category: "Furniture",
    quarter: "Q1",
    year: 2024,
    sales: 10200,
  },
  {
    id: 8,
    region: "North",
    category: "Furniture",
    quarter: "Q2",
    year: 2024,
    sales: 11000,
  },
  {
    id: 9,
    region: "South",
    category: "Electronics",
    quarter: "Q1",
    year: 2023,
    sales: 9800,
  },
  {
    id: 10,
    region: "South",
    category: "Electronics",
    quarter: "Q2",
    year: 2023,
    sales: 11200,
  },
  {
    id: 11,
    region: "South",
    category: "Electronics",
    quarter: "Q1",
    year: 2024,
    sales: 12500,
  },
  {
    id: 12,
    region: "South",
    category: "Electronics",
    quarter: "Q2",
    year: 2024,
    sales: 13900,
  },
  {
    id: 13,
    region: "South",
    category: "Furniture",
    quarter: "Q1",
    year: 2023,
    sales: 7300,
  },
  {
    id: 14,
    region: "South",
    category: "Furniture",
    quarter: "Q2",
    year: 2023,
    sales: 7800,
  },
  {
    id: 15,
    region: "South",
    category: "Furniture",
    quarter: "Q1",
    year: 2024,
    sales: 8500,
  },
  {
    id: 16,
    region: "South",
    category: "Furniture",
    quarter: "Q2",
    year: 2024,
    sales: 9200,
  },
  {
    id: 17,
    region: "East",
    category: "Electronics",
    quarter: "Q1",
    year: 2023,
    sales: 10500,
  },
  {
    id: 18,
    region: "East",
    category: "Electronics",
    quarter: "Q2",
    year: 2023,
    sales: 11800,
  },
  {
    id: 19,
    region: "East",
    category: "Electronics",
    quarter: "Q1",
    year: 2024,
    sales: 13400,
  },
  {
    id: 20,
    region: "East",
    category: "Electronics",
    quarter: "Q2",
    year: 2024,
    sales: 14700,
  },
  {
    id: 21,
    region: "East",
    category: "Furniture",
    quarter: "Q1",
    year: 2023,
    sales: 11200,
  },
  {
    id: 22,
    region: "East",
    category: "Furniture",
    quarter: "Q2",
    year: 2023,
    sales: 12000,
  },
  {
    id: 23,
    region: "East",
    category: "Furniture",
    quarter: "Q1",
    year: 2024,
    sales: 13100,
  },
  {
    id: 24,
    region: "East",
    category: "Furniture",
    quarter: "Q2",
    year: 2024,
    sales: 14300,
  },
  {
    id: 25,
    region: "West",
    category: "Electronics",
    quarter: "Q1",
    year: 2023,
    sales: 11300,
  },
  {
    id: 26,
    region: "West",
    category: "Electronics",
    quarter: "Q2",
    year: 2023,
    sales: 12600,
  },
  {
    id: 27,
    region: "West",
    category: "Electronics",
    quarter: "Q1",
    year: 2024,
    sales: 14100,
  },
  {
    id: 28,
    region: "West",
    category: "Electronics",
    quarter: "Q2",
    year: 2024,
    sales: 15500,
  },
  {
    id: 29,
    region: "West",
    category: "Furniture",
    quarter: "Q1",
    year: 2023,
    sales: 8200,
  },
  {
    id: 30,
    region: "West",
    category: "Furniture",
    quarter: "Q2",
    year: 2023,
    sales: 8900,
  },
  {
    id: 31,
    region: "West",
    category: "Furniture",
    quarter: "Q1",
    year: 2024,
    sales: 9700,
  },
  {
    id: 32,
    region: "West",
    category: "Furniture",
    quarter: "Q2",
    year: 2024,
    sales: 10500,
  },
];
